### ISSUE TITLE
petpet可以像avatar一样直接指令嘛，不用这个 / 为触发

### ISSUE THREAD

**Issue by 3273576540** [chingkingm/Hoshinobot-plugin-petpet#1]

**Comment by chingkingm** [comment]
可以实现，但可能会错误捕获非命令的日常对话，也就是说，可能群友发了个“吃”，然后bot就触发了，因为没有参数就返回一句“出错了，请稍后重试”。
你如果不在乎这样的情况，可以修改触发器为on_message()
