### ISSUE TITLE
抛开错误不谈

### ISSUE THREAD

**Issue by Mei-Sakura** [chingkingm/Hoshinobot-plugin-petpet#5]
其实我并不是来提问题的~~~
![05}C5WYN_IQ@572AA SXI3E](https://user-images.githubusercontent.com/81066884/157649094-777ff8fd-4308-45c9-b442-46d094d58faa.gif)
群友们属实是对这个功能赞不绝口，建议多来点~~~
![0Q`PF2`4B`RJ`S`%U0I9OHJ](https://user-images.githubusercontent.com/81066884/157649222-f5438ed6-348b-4bb1-bca1-187ea15a5cc3.jpg)

**Comment by chingkingm** [comment]
感谢，不过我只是搬运的，可以到源仓库点star支持(o^^o)♪
