### ISSUE TITLE
部署出现问题，并且已经安装所有依赖了

### ISSUE THREAD

**Issue by Putarku** [chingkingm/Hoshinobot-plugin-petpet#7]
![image](https://user-images.githubusercontent.com/66679443/158017714-4db79d33-9e66-48e8-97b1-8d4c76ff4065.png)

**Comment by chingkingm** [comment]
可能是numpy版本低了，需要大于1.2.0
imageio要高于2.12.0

**Comment by Putarku** [comment]
![image](https://user-images.githubusercontent.com/66679443/158043970-8af10755-f3fd-4ec6-882f-9e2321e7ec3f.png)
![image](https://user-images.githubusercontent.com/66679443/158043972-64c2f59a-2a7b-48bf-a21b-f98a30960559.png)
就emmm还是不行

**Comment by chingkingm** [comment]
没有头绪。。
